name: Docker build and push images to docker hub

# Trigger qui dÃ©clenchent l'action
on:
  push:
    branches: [ "main" ]
    paths:
      - 'k8s/**'
      - 'app/**'
  pull_request:
    branches: [ "main" ]

# Variable d'environnement
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-actions-dockerhub-argo
  K8S_PATH: k8s/deployment.yml


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate image tag from commit SHA
        run: |
          TAG=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./app
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Install cosign before signature
      - name: Install cosign 
        uses: sigstore/cosign-installer@v3.5.0
      
      # Sign the Docker image to guarantee its integrity and provenance after push 
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          cosign sign --yes ${IMAGE}@${DIGEST}
          
      - name: Replace image tag by new sha
        run: |
          sed -i "s|image: .*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|" ${{ env.K8S_PATH }}

      - name: Check sed
        run: cat ${{ env.K8S_PATH }}

      - name: Commit and push 
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore(k8s): update image to ${{ env.IMAGE_TAG }} in deployment.yml"
          git push
